server:
  port: 7002

eureka:
  instance:
    #    集群
    hostname: eureka7002.com
  # 单机
  #    hostname: localhost
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置Eureka Server的地址查询服务和注册服务都需要这个地址
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka